extends:
  - airbnb-base
  - prettier

parser: babel-eslint

env:
  node: true

rules:
  no-mixed-operators: 0 # incompatible with prettier
  no-confusing-arrow: 0 # incompatible with prettier
  max-len: 0 # prefer prettier
